version: "3"
services:
  springboot-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: myspringboot
      MYSQL_PASSWORD: 3219
    networks:
      - springboot_mysql_net


  mysqldb :
    container_name: mysqldb
    image : "mysql"
    command: --init-file /var/lib/mysql/init.sql
    volumes:
      - /Users/solsol/ASAC_assignment/demo/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: myfirstdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - springboot_mysql_net

networks:
  springboot_mysql_net:
    driver: bridge